// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/novaroute.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerType int32

const (
	PeerType_PEER_TYPE_UNSPECIFIED PeerType = 0
	PeerType_PEER_TYPE_EXTERNAL    PeerType = 1
	PeerType_PEER_TYPE_INTERNAL    PeerType = 2
)

// Enum value maps for PeerType.
var (
	PeerType_name = map[int32]string{
		0: "PEER_TYPE_UNSPECIFIED",
		1: "PEER_TYPE_EXTERNAL",
		2: "PEER_TYPE_INTERNAL",
	}
	PeerType_value = map[string]int32{
		"PEER_TYPE_UNSPECIFIED": 0,
		"PEER_TYPE_EXTERNAL":    1,
		"PEER_TYPE_INTERNAL":    2,
	}
)

func (x PeerType) Enum() *PeerType {
	p := new(PeerType)
	*p = x
	return p
}

func (x PeerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_novaroute_proto_enumTypes[0].Descriptor()
}

func (PeerType) Type() protoreflect.EnumType {
	return &file_api_v1_novaroute_proto_enumTypes[0]
}

func (x PeerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerType.Descriptor instead.
func (PeerType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{0}
}

type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_UNSPECIFIED  AddressFamily = 0
	AddressFamily_ADDRESS_FAMILY_IPV4_UNICAST AddressFamily = 1
	AddressFamily_ADDRESS_FAMILY_IPV6_UNICAST AddressFamily = 2
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ADDRESS_FAMILY_UNSPECIFIED",
		1: "ADDRESS_FAMILY_IPV4_UNICAST",
		2: "ADDRESS_FAMILY_IPV6_UNICAST",
	}
	AddressFamily_value = map[string]int32{
		"ADDRESS_FAMILY_UNSPECIFIED":  0,
		"ADDRESS_FAMILY_IPV4_UNICAST": 1,
		"ADDRESS_FAMILY_IPV6_UNICAST": 2,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_novaroute_proto_enumTypes[1].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_api_v1_novaroute_proto_enumTypes[1]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressFamily.Descriptor instead.
func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{1}
}

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_BGP         Protocol = 1
	Protocol_PROTOCOL_OSPF        Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_BGP",
		2: "PROTOCOL_OSPF",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_BGP":         1,
		"PROTOCOL_OSPF":        2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_novaroute_proto_enumTypes[2].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_v1_novaroute_proto_enumTypes[2]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED        EventType = 0
	EventType_EVENT_TYPE_PEER_UP            EventType = 1
	EventType_EVENT_TYPE_PEER_DOWN          EventType = 2
	EventType_EVENT_TYPE_PREFIX_ADVERTISED  EventType = 3
	EventType_EVENT_TYPE_PREFIX_WITHDRAWN   EventType = 4
	EventType_EVENT_TYPE_BFD_UP             EventType = 5
	EventType_EVENT_TYPE_BFD_DOWN           EventType = 6
	EventType_EVENT_TYPE_OSPF_NEIGHBOR_UP   EventType = 7
	EventType_EVENT_TYPE_OSPF_NEIGHBOR_DOWN EventType = 8
	EventType_EVENT_TYPE_FRR_CONNECTED      EventType = 9
	EventType_EVENT_TYPE_FRR_DISCONNECTED   EventType = 10
	EventType_EVENT_TYPE_OWNER_REGISTERED   EventType = 11
	EventType_EVENT_TYPE_OWNER_DEREGISTERED EventType = 12
	EventType_EVENT_TYPE_POLICY_VIOLATION   EventType = 13
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PEER_UP",
		2:  "EVENT_TYPE_PEER_DOWN",
		3:  "EVENT_TYPE_PREFIX_ADVERTISED",
		4:  "EVENT_TYPE_PREFIX_WITHDRAWN",
		5:  "EVENT_TYPE_BFD_UP",
		6:  "EVENT_TYPE_BFD_DOWN",
		7:  "EVENT_TYPE_OSPF_NEIGHBOR_UP",
		8:  "EVENT_TYPE_OSPF_NEIGHBOR_DOWN",
		9:  "EVENT_TYPE_FRR_CONNECTED",
		10: "EVENT_TYPE_FRR_DISCONNECTED",
		11: "EVENT_TYPE_OWNER_REGISTERED",
		12: "EVENT_TYPE_OWNER_DEREGISTERED",
		13: "EVENT_TYPE_POLICY_VIOLATION",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_TYPE_PEER_UP":            1,
		"EVENT_TYPE_PEER_DOWN":          2,
		"EVENT_TYPE_PREFIX_ADVERTISED":  3,
		"EVENT_TYPE_PREFIX_WITHDRAWN":   4,
		"EVENT_TYPE_BFD_UP":             5,
		"EVENT_TYPE_BFD_DOWN":           6,
		"EVENT_TYPE_OSPF_NEIGHBOR_UP":   7,
		"EVENT_TYPE_OSPF_NEIGHBOR_DOWN": 8,
		"EVENT_TYPE_FRR_CONNECTED":      9,
		"EVENT_TYPE_FRR_DISCONNECTED":   10,
		"EVENT_TYPE_OWNER_REGISTERED":   11,
		"EVENT_TYPE_OWNER_DEREGISTERED": 12,
		"EVENT_TYPE_POLICY_VIOLATION":   13,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_novaroute_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_v1_novaroute_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ReassertIntents bool                   `protobuf:"varint,3,opt,name=reassert_intents,json=reassertIntents,proto3" json:"reassert_intents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetReassertIntents() bool {
	if x != nil {
		return x.ReassertIntents
	}
	return false
}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CurrentPrefixes []string               `protobuf:"bytes,2,rep,name=current_prefixes,json=currentPrefixes,proto3" json:"current_prefixes,omitempty"`
	CurrentPeers    []string               `protobuf:"bytes,3,rep,name=current_peers,json=currentPeers,proto3" json:"current_peers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetCurrentPrefixes() []string {
	if x != nil {
		return x.CurrentPrefixes
	}
	return nil
}

func (x *RegisterResponse) GetCurrentPeers() []string {
	if x != nil {
		return x.CurrentPeers
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	WithdrawAll   bool                   `protobuf:"varint,3,opt,name=withdraw_all,json=withdrawAll,proto3" json:"withdraw_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeregisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeregisterRequest) GetWithdrawAll() bool {
	if x != nil {
		return x.WithdrawAll
	}
	return false
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{3}
}

type ConfigureBGPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	LocalAs       uint32                 `protobuf:"varint,3,opt,name=local_as,json=localAs,proto3" json:"local_as,omitempty"`
	RouterId      string                 `protobuf:"bytes,4,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureBGPRequest) Reset() {
	*x = ConfigureBGPRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBGPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBGPRequest) ProtoMessage() {}

func (x *ConfigureBGPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureBGPRequest.ProtoReflect.Descriptor instead.
func (*ConfigureBGPRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureBGPRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ConfigureBGPRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfigureBGPRequest) GetLocalAs() uint32 {
	if x != nil {
		return x.LocalAs
	}
	return 0
}

func (x *ConfigureBGPRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

type ConfigureBGPResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PreviousAs       uint32                 `protobuf:"varint,1,opt,name=previous_as,json=previousAs,proto3" json:"previous_as,omitempty"`
	PreviousRouterId string                 `protobuf:"bytes,2,opt,name=previous_router_id,json=previousRouterId,proto3" json:"previous_router_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigureBGPResponse) Reset() {
	*x = ConfigureBGPResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBGPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBGPResponse) ProtoMessage() {}

func (x *ConfigureBGPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureBGPResponse.ProtoReflect.Descriptor instead.
func (*ConfigureBGPResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureBGPResponse) GetPreviousAs() uint32 {
	if x != nil {
		return x.PreviousAs
	}
	return 0
}

func (x *ConfigureBGPResponse) GetPreviousRouterId() string {
	if x != nil {
		return x.PreviousRouterId
	}
	return ""
}

type ApplyPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Peer          *BGPPeer               `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPeerRequest) Reset() {
	*x = ApplyPeerRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPeerRequest) ProtoMessage() {}

func (x *ApplyPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPeerRequest.ProtoReflect.Descriptor instead.
func (*ApplyPeerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyPeerRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ApplyPeerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApplyPeerRequest) GetPeer() *BGPPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type BGPPeer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NeighborAddress string                 `protobuf:"bytes,1,opt,name=neighbor_address,json=neighborAddress,proto3" json:"neighbor_address,omitempty"`
	RemoteAs        uint32                 `protobuf:"varint,2,opt,name=remote_as,json=remoteAs,proto3" json:"remote_as,omitempty"`
	PeerType        PeerType               `protobuf:"varint,3,opt,name=peer_type,json=peerType,proto3,enum=novaroute.v1.PeerType" json:"peer_type,omitempty"`
	Keepalive       uint32                 `protobuf:"varint,4,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	HoldTime        uint32                 `protobuf:"varint,5,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	BfdEnabled      bool                   `protobuf:"varint,6,opt,name=bfd_enabled,json=bfdEnabled,proto3" json:"bfd_enabled,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	AddressFamilies []AddressFamily        `protobuf:"varint,8,rep,packed,name=address_families,json=addressFamilies,proto3,enum=novaroute.v1.AddressFamily" json:"address_families,omitempty"`
	SourceAddress   string                 `protobuf:"bytes,9,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	EbgpMultihop    uint32                 `protobuf:"varint,10,opt,name=ebgp_multihop,json=ebgpMultihop,proto3" json:"ebgp_multihop,omitempty"`
	Password        string                 `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BGPPeer) Reset() {
	*x = BGPPeer{}
	mi := &file_api_v1_novaroute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPPeer) ProtoMessage() {}

func (x *BGPPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPPeer.ProtoReflect.Descriptor instead.
func (*BGPPeer) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{7}
}

func (x *BGPPeer) GetNeighborAddress() string {
	if x != nil {
		return x.NeighborAddress
	}
	return ""
}

func (x *BGPPeer) GetRemoteAs() uint32 {
	if x != nil {
		return x.RemoteAs
	}
	return 0
}

func (x *BGPPeer) GetPeerType() PeerType {
	if x != nil {
		return x.PeerType
	}
	return PeerType_PEER_TYPE_UNSPECIFIED
}

func (x *BGPPeer) GetKeepalive() uint32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

func (x *BGPPeer) GetHoldTime() uint32 {
	if x != nil {
		return x.HoldTime
	}
	return 0
}

func (x *BGPPeer) GetBfdEnabled() bool {
	if x != nil {
		return x.BfdEnabled
	}
	return false
}

func (x *BGPPeer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BGPPeer) GetAddressFamilies() []AddressFamily {
	if x != nil {
		return x.AddressFamilies
	}
	return nil
}

func (x *BGPPeer) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *BGPPeer) GetEbgpMultihop() uint32 {
	if x != nil {
		return x.EbgpMultihop
	}
	return 0
}

func (x *BGPPeer) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ApplyPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPeerResponse) Reset() {
	*x = ApplyPeerResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPeerResponse) ProtoMessage() {}

func (x *ApplyPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPeerResponse.ProtoReflect.Descriptor instead.
func (*ApplyPeerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{8}
}

type RemovePeerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NeighborAddress string                 `protobuf:"bytes,3,opt,name=neighbor_address,json=neighborAddress,proto3" json:"neighbor_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePeerRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RemovePeerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemovePeerRequest) GetNeighborAddress() string {
	if x != nil {
		return x.NeighborAddress
	}
	return ""
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{10}
}

type AdvertisePrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Protocol      Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=novaroute.v1.Protocol" json:"protocol,omitempty"`
	Attributes    *PrefixAttributes      `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertisePrefixRequest) Reset() {
	*x = AdvertisePrefixRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertisePrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertisePrefixRequest) ProtoMessage() {}

func (x *AdvertisePrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertisePrefixRequest.ProtoReflect.Descriptor instead.
func (*AdvertisePrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{11}
}

func (x *AdvertisePrefixRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AdvertisePrefixRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdvertisePrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AdvertisePrefixRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *AdvertisePrefixRequest) GetAttributes() *PrefixAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PrefixAttributes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalPreference uint32                 `protobuf:"varint,1,opt,name=local_preference,json=localPreference,proto3" json:"local_preference,omitempty"`
	Communities     []string               `protobuf:"bytes,2,rep,name=communities,proto3" json:"communities,omitempty"`
	Med             uint32                 `protobuf:"varint,3,opt,name=med,proto3" json:"med,omitempty"`
	NextHop         string                 `protobuf:"bytes,4,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrefixAttributes) Reset() {
	*x = PrefixAttributes{}
	mi := &file_api_v1_novaroute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixAttributes) ProtoMessage() {}

func (x *PrefixAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixAttributes.ProtoReflect.Descriptor instead.
func (*PrefixAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{12}
}

func (x *PrefixAttributes) GetLocalPreference() uint32 {
	if x != nil {
		return x.LocalPreference
	}
	return 0
}

func (x *PrefixAttributes) GetCommunities() []string {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *PrefixAttributes) GetMed() uint32 {
	if x != nil {
		return x.Med
	}
	return 0
}

func (x *PrefixAttributes) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

type AdvertisePrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertisePrefixResponse) Reset() {
	*x = AdvertisePrefixResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertisePrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertisePrefixResponse) ProtoMessage() {}

func (x *AdvertisePrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertisePrefixResponse.ProtoReflect.Descriptor instead.
func (*AdvertisePrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{13}
}

type WithdrawPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Protocol      Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=novaroute.v1.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawPrefixRequest) Reset() {
	*x = WithdrawPrefixRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawPrefixRequest) ProtoMessage() {}

func (x *WithdrawPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawPrefixRequest.ProtoReflect.Descriptor instead.
func (*WithdrawPrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawPrefixRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WithdrawPrefixRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WithdrawPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *WithdrawPrefixRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type WithdrawPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawPrefixResponse) Reset() {
	*x = WithdrawPrefixResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawPrefixResponse) ProtoMessage() {}

func (x *WithdrawPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawPrefixResponse.ProtoReflect.Descriptor instead.
func (*WithdrawPrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{15}
}

type EnableBFDRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Owner            string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token            string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PeerAddress      string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	MinRxMs          uint32                 `protobuf:"varint,4,opt,name=min_rx_ms,json=minRxMs,proto3" json:"min_rx_ms,omitempty"`
	MinTxMs          uint32                 `protobuf:"varint,5,opt,name=min_tx_ms,json=minTxMs,proto3" json:"min_tx_ms,omitempty"`
	DetectMultiplier uint32                 `protobuf:"varint,6,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	InterfaceName    string                 `protobuf:"bytes,7,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnableBFDRequest) Reset() {
	*x = EnableBFDRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableBFDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableBFDRequest) ProtoMessage() {}

func (x *EnableBFDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableBFDRequest.ProtoReflect.Descriptor instead.
func (*EnableBFDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{16}
}

func (x *EnableBFDRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *EnableBFDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnableBFDRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *EnableBFDRequest) GetMinRxMs() uint32 {
	if x != nil {
		return x.MinRxMs
	}
	return 0
}

func (x *EnableBFDRequest) GetMinTxMs() uint32 {
	if x != nil {
		return x.MinTxMs
	}
	return 0
}

func (x *EnableBFDRequest) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *EnableBFDRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type EnableBFDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableBFDResponse) Reset() {
	*x = EnableBFDResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableBFDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableBFDResponse) ProtoMessage() {}

func (x *EnableBFDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableBFDResponse.ProtoReflect.Descriptor instead.
func (*EnableBFDResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{17}
}

type DisableBFDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PeerAddress   string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableBFDRequest) Reset() {
	*x = DisableBFDRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableBFDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBFDRequest) ProtoMessage() {}

func (x *DisableBFDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBFDRequest.ProtoReflect.Descriptor instead.
func (*DisableBFDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{18}
}

func (x *DisableBFDRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DisableBFDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DisableBFDRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

type DisableBFDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableBFDResponse) Reset() {
	*x = DisableBFDResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableBFDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBFDResponse) ProtoMessage() {}

func (x *DisableBFDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBFDResponse.ProtoReflect.Descriptor instead.
func (*DisableBFDResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{19}
}

type EnableOSPFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	AreaId        string                 `protobuf:"bytes,4,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Passive       bool                   `protobuf:"varint,5,opt,name=passive,proto3" json:"passive,omitempty"`
	Cost          uint32                 `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	HelloInterval uint32                 `protobuf:"varint,7,opt,name=hello_interval,json=helloInterval,proto3" json:"hello_interval,omitempty"`
	DeadInterval  uint32                 `protobuf:"varint,8,opt,name=dead_interval,json=deadInterval,proto3" json:"dead_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableOSPFRequest) Reset() {
	*x = EnableOSPFRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableOSPFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOSPFRequest) ProtoMessage() {}

func (x *EnableOSPFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOSPFRequest.ProtoReflect.Descriptor instead.
func (*EnableOSPFRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{20}
}

func (x *EnableOSPFRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *EnableOSPFRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnableOSPFRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *EnableOSPFRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *EnableOSPFRequest) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *EnableOSPFRequest) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *EnableOSPFRequest) GetHelloInterval() uint32 {
	if x != nil {
		return x.HelloInterval
	}
	return 0
}

func (x *EnableOSPFRequest) GetDeadInterval() uint32 {
	if x != nil {
		return x.DeadInterval
	}
	return 0
}

type EnableOSPFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableOSPFResponse) Reset() {
	*x = EnableOSPFResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableOSPFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOSPFResponse) ProtoMessage() {}

func (x *EnableOSPFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOSPFResponse.ProtoReflect.Descriptor instead.
func (*EnableOSPFResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{21}
}

type DisableOSPFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableOSPFRequest) Reset() {
	*x = DisableOSPFRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableOSPFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOSPFRequest) ProtoMessage() {}

func (x *DisableOSPFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOSPFRequest.ProtoReflect.Descriptor instead.
func (*DisableOSPFRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{22}
}

func (x *DisableOSPFRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DisableOSPFRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DisableOSPFRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type DisableOSPFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableOSPFResponse) Reset() {
	*x = DisableOSPFResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableOSPFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOSPFResponse) ProtoMessage() {}

func (x *DisableOSPFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOSPFResponse.ProtoReflect.Descriptor instead.
func (*DisableOSPFResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{23}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerFilter   string                 `protobuf:"bytes,1,opt,name=owner_filter,json=ownerFilter,proto3" json:"owner_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{24}
}

func (x *GetStatusRequest) GetOwnerFilter() string {
	if x != nil {
		return x.OwnerFilter
	}
	return ""
}

type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peers          []*PeerStatus          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Prefixes       []*PrefixStatus        `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	BfdSessions    []*BFDSessionStatus    `protobuf:"bytes,3,rep,name=bfd_sessions,json=bfdSessions,proto3" json:"bfd_sessions,omitempty"`
	OspfInterfaces []*OSPFInterfaceStatus `protobuf:"bytes,4,rep,name=ospf_interfaces,json=ospfInterfaces,proto3" json:"ospf_interfaces,omitempty"`
	FrrStatus      *FRRStatus             `protobuf:"bytes,5,opt,name=frr_status,json=frrStatus,proto3" json:"frr_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_v1_novaroute_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{25}
}

func (x *GetStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetStatusResponse) GetPrefixes() []*PrefixStatus {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *GetStatusResponse) GetBfdSessions() []*BFDSessionStatus {
	if x != nil {
		return x.BfdSessions
	}
	return nil
}

func (x *GetStatusResponse) GetOspfInterfaces() []*OSPFInterfaceStatus {
	if x != nil {
		return x.OspfInterfaces
	}
	return nil
}

func (x *GetStatusResponse) GetFrrStatus() *FRRStatus {
	if x != nil {
		return x.FrrStatus
	}
	return nil
}

type PeerStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NeighborAddress  string                 `protobuf:"bytes,1,opt,name=neighbor_address,json=neighborAddress,proto3" json:"neighbor_address,omitempty"`
	RemoteAs         uint32                 `protobuf:"varint,2,opt,name=remote_as,json=remoteAs,proto3" json:"remote_as,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Owner            string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	PrefixesReceived uint32                 `protobuf:"varint,5,opt,name=prefixes_received,json=prefixesReceived,proto3" json:"prefixes_received,omitempty"`
	PrefixesSent     uint32                 `protobuf:"varint,6,opt,name=prefixes_sent,json=prefixesSent,proto3" json:"prefixes_sent,omitempty"`
	Uptime           string                 `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BfdEnabled       bool                   `protobuf:"varint,8,opt,name=bfd_enabled,json=bfdEnabled,proto3" json:"bfd_enabled,omitempty"`
	BfdStatus        string                 `protobuf:"bytes,9,opt,name=bfd_status,json=bfdStatus,proto3" json:"bfd_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_api_v1_novaroute_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{26}
}

func (x *PeerStatus) GetNeighborAddress() string {
	if x != nil {
		return x.NeighborAddress
	}
	return ""
}

func (x *PeerStatus) GetRemoteAs() uint32 {
	if x != nil {
		return x.RemoteAs
	}
	return 0
}

func (x *PeerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PeerStatus) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PeerStatus) GetPrefixesReceived() uint32 {
	if x != nil {
		return x.PrefixesReceived
	}
	return 0
}

func (x *PeerStatus) GetPrefixesSent() uint32 {
	if x != nil {
		return x.PrefixesSent
	}
	return 0
}

func (x *PeerStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *PeerStatus) GetBfdEnabled() bool {
	if x != nil {
		return x.BfdEnabled
	}
	return false
}

func (x *PeerStatus) GetBfdStatus() string {
	if x != nil {
		return x.BfdStatus
	}
	return ""
}

type PrefixStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=novaroute.v1.Protocol" json:"protocol,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixStatus) Reset() {
	*x = PrefixStatus{}
	mi := &file_api_v1_novaroute_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixStatus) ProtoMessage() {}

func (x *PrefixStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixStatus.ProtoReflect.Descriptor instead.
func (*PrefixStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{27}
}

func (x *PrefixStatus) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixStatus) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PrefixStatus) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PrefixStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type BFDSessionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress      string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Owner            string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	MinRxMs          uint32                 `protobuf:"varint,4,opt,name=min_rx_ms,json=minRxMs,proto3" json:"min_rx_ms,omitempty"`
	MinTxMs          uint32                 `protobuf:"varint,5,opt,name=min_tx_ms,json=minTxMs,proto3" json:"min_tx_ms,omitempty"`
	DetectMultiplier uint32                 `protobuf:"varint,6,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	Uptime           string                 `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BFDSessionStatus) Reset() {
	*x = BFDSessionStatus{}
	mi := &file_api_v1_novaroute_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFDSessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFDSessionStatus) ProtoMessage() {}

func (x *BFDSessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFDSessionStatus.ProtoReflect.Descriptor instead.
func (*BFDSessionStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{28}
}

func (x *BFDSessionStatus) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *BFDSessionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BFDSessionStatus) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BFDSessionStatus) GetMinRxMs() uint32 {
	if x != nil {
		return x.MinRxMs
	}
	return 0
}

func (x *BFDSessionStatus) GetMinTxMs() uint32 {
	if x != nil {
		return x.MinTxMs
	}
	return 0
}

func (x *BFDSessionStatus) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *BFDSessionStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type OSPFInterfaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	AreaId        string                 `protobuf:"bytes,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	NeighborCount uint32                 `protobuf:"varint,5,opt,name=neighbor_count,json=neighborCount,proto3" json:"neighbor_count,omitempty"`
	Cost          uint32                 `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInterfaceStatus) Reset() {
	*x = OSPFInterfaceStatus{}
	mi := &file_api_v1_novaroute_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInterfaceStatus) ProtoMessage() {}

func (x *OSPFInterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInterfaceStatus.ProtoReflect.Descriptor instead.
func (*OSPFInterfaceStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{29}
}

func (x *OSPFInterfaceStatus) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *OSPFInterfaceStatus) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *OSPFInterfaceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OSPFInterfaceStatus) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OSPFInterfaceStatus) GetNeighborCount() uint32 {
	if x != nil {
		return x.NeighborCount
	}
	return 0
}

func (x *OSPFInterfaceStatus) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type FRRStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FRRStatus) Reset() {
	*x = FRRStatus{}
	mi := &file_api_v1_novaroute_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FRRStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FRRStatus) ProtoMessage() {}

func (x *FRRStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FRRStatus.ProtoReflect.Descriptor instead.
func (*FRRStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{30}
}

func (x *FRRStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FRRStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *FRRStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerFilter   string                 `protobuf:"bytes,1,opt,name=owner_filter,json=ownerFilter,proto3" json:"owner_filter,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_api_v1_novaroute_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{31}
}

func (x *StreamEventsRequest) GetOwnerFilter() string {
	if x != nil {
		return x.OwnerFilter
	}
	return ""
}

func (x *StreamEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type RouteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=novaroute.v1.EventType" json:"type,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEvent) Reset() {
	*x = RouteEvent{}
	mi := &file_api_v1_novaroute_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEvent) ProtoMessage() {}

func (x *RouteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_novaroute_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEvent.ProtoReflect.Descriptor instead.
func (*RouteEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_novaroute_proto_rawDescGZIP(), []int{32}
}

func (x *RouteEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RouteEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *RouteEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *RouteEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RouteEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_v1_novaroute_proto protoreflect.FileDescriptor

const file_api_v1_novaroute_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/novaroute.proto\x12\fnovaroute.v1\"h\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12)\n" +
	"\x10reassert_intents\x18\x03 \x01(\bR\x0freassertIntents\"\x81\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10current_prefixes\x18\x02 \x03(\tR\x0fcurrentPrefixes\x12#\n" +
	"\rcurrent_peers\x18\x03 \x03(\tR\fcurrentPeers\"b\n" +
	"\x11DeregisterRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fwithdraw_all\x18\x03 \x01(\bR\vwithdrawAll\"\x14\n" +
	"\x12DeregisterResponse\"y\n" +
	"\x13ConfigureBGPRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\blocal_as\x18\x03 \x01(\rR\alocalAs\x12\x1b\n" +
	"\trouter_id\x18\x04 \x01(\tR\brouterId\"e\n" +
	"\x14ConfigureBGPResponse\x12\x1f\n" +
	"\vprevious_as\x18\x01 \x01(\rR\n" +
	"previousAs\x12,\n" +
	"\x12previous_router_id\x18\x02 \x01(\tR\x10previousRouterId\"i\n" +
	"\x10ApplyPeerRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12)\n" +
	"\x04peer\x18\x03 \x01(\v2\x15.novaroute.v1.BGPPeerR\x04peer\"\xb4\x03\n" +
	"\aBGPPeer\x12)\n" +
	"\x10neighbor_address\x18\x01 \x01(\tR\x0fneighborAddress\x12\x1b\n" +
	"\tremote_as\x18\x02 \x01(\rR\bremoteAs\x123\n" +
	"\tpeer_type\x18\x03 \x01(\x0e2\x16.novaroute.v1.PeerTypeR\bpeerType\x12\x1c\n" +
	"\tkeepalive\x18\x04 \x01(\rR\tkeepalive\x12\x1b\n" +
	"\thold_time\x18\x05 \x01(\rR\bholdTime\x12\x1f\n" +
	"\vbfd_enabled\x18\x06 \x01(\bR\n" +
	"bfdEnabled\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12F\n" +
	"\x10address_families\x18\b \x03(\x0e2\x1b.novaroute.v1.AddressFamilyR\x0faddressFamilies\x12%\n" +
	"\x0esource_address\x18\t \x01(\tR\rsourceAddress\x12#\n" +
	"\rebgp_multihop\x18\n" +
	" \x01(\rR\febgpMultihop\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\"\x13\n" +
	"\x11ApplyPeerResponse\"j\n" +
	"\x11RemovePeerRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12)\n" +
	"\x10neighbor_address\x18\x03 \x01(\tR\x0fneighborAddress\"\x14\n" +
	"\x12RemovePeerResponse\"\xd0\x01\n" +
	"\x16AdvertisePrefixRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x122\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x16.novaroute.v1.ProtocolR\bprotocol\x12>\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x1e.novaroute.v1.PrefixAttributesR\n" +
	"attributes\"\x8c\x01\n" +
	"\x10PrefixAttributes\x12)\n" +
	"\x10local_preference\x18\x01 \x01(\rR\x0flocalPreference\x12 \n" +
	"\vcommunities\x18\x02 \x03(\tR\vcommunities\x12\x10\n" +
	"\x03med\x18\x03 \x01(\rR\x03med\x12\x19\n" +
	"\bnext_hop\x18\x04 \x01(\tR\anextHop\"\x19\n" +
	"\x17AdvertisePrefixResponse\"\x8f\x01\n" +
	"\x15WithdrawPrefixRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x122\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x16.novaroute.v1.ProtocolR\bprotocol\"\x18\n" +
	"\x16WithdrawPrefixResponse\"\xed\x01\n" +
	"\x10EnableBFDRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fpeer_address\x18\x03 \x01(\tR\vpeerAddress\x12\x1a\n" +
	"\tmin_rx_ms\x18\x04 \x01(\rR\aminRxMs\x12\x1a\n" +
	"\tmin_tx_ms\x18\x05 \x01(\rR\aminTxMs\x12+\n" +
	"\x11detect_multiplier\x18\x06 \x01(\rR\x10detectMultiplier\x12%\n" +
	"\x0einterface_name\x18\a \x01(\tR\rinterfaceName\"\x13\n" +
	"\x11EnableBFDResponse\"b\n" +
	"\x11DisableBFDRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fpeer_address\x18\x03 \x01(\tR\vpeerAddress\"\x14\n" +
	"\x12DisableBFDResponse\"\xf9\x01\n" +
	"\x11EnableOSPFRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12\x17\n" +
	"\aarea_id\x18\x04 \x01(\tR\x06areaId\x12\x18\n" +
	"\apassive\x18\x05 \x01(\bR\apassive\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\rR\x04cost\x12%\n" +
	"\x0ehello_interval\x18\a \x01(\rR\rhelloInterval\x12#\n" +
	"\rdead_interval\x18\b \x01(\rR\fdeadInterval\"\x14\n" +
	"\x12EnableOSPFResponse\"g\n" +
	"\x12DisableOSPFRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\"\x15\n" +
	"\x13DisableOSPFResponse\"5\n" +
	"\x10GetStatusRequest\x12!\n" +
	"\fowner_filter\x18\x01 \x01(\tR\vownerFilter\"\xc2\x02\n" +
	"\x11GetStatusResponse\x12.\n" +
	"\x05peers\x18\x01 \x03(\v2\x18.novaroute.v1.PeerStatusR\x05peers\x126\n" +
	"\bprefixes\x18\x02 \x03(\v2\x1a.novaroute.v1.PrefixStatusR\bprefixes\x12A\n" +
	"\fbfd_sessions\x18\x03 \x03(\v2\x1e.novaroute.v1.BFDSessionStatusR\vbfdSessions\x12J\n" +
	"\x0fospf_interfaces\x18\x04 \x03(\v2!.novaroute.v1.OSPFInterfaceStatusR\x0eospfInterfaces\x126\n" +
	"\n" +
	"frr_status\x18\x05 \x01(\v2\x17.novaroute.v1.FRRStatusR\tfrrStatus\"\xaa\x02\n" +
	"\n" +
	"PeerStatus\x12)\n" +
	"\x10neighbor_address\x18\x01 \x01(\tR\x0fneighborAddress\x12\x1b\n" +
	"\tremote_as\x18\x02 \x01(\rR\bremoteAs\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12+\n" +
	"\x11prefixes_received\x18\x05 \x01(\rR\x10prefixesReceived\x12#\n" +
	"\rprefixes_sent\x18\x06 \x01(\rR\fprefixesSent\x12\x16\n" +
	"\x06uptime\x18\a \x01(\tR\x06uptime\x12\x1f\n" +
	"\vbfd_enabled\x18\b \x01(\bR\n" +
	"bfdEnabled\x12\x1d\n" +
	"\n" +
	"bfd_status\x18\t \x01(\tR\tbfdStatus\"\x86\x01\n" +
	"\fPrefixStatus\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x122\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x16.novaroute.v1.ProtocolR\bprotocol\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\xde\x01\n" +
	"\x10BFDSessionStatus\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1a\n" +
	"\tmin_rx_ms\x18\x04 \x01(\rR\aminRxMs\x12\x1a\n" +
	"\tmin_tx_ms\x18\x05 \x01(\rR\aminTxMs\x12+\n" +
	"\x11detect_multiplier\x18\x06 \x01(\rR\x10detectMultiplier\x12\x16\n" +
	"\x06uptime\x18\a \x01(\tR\x06uptime\"\xbc\x01\n" +
	"\x13OSPFInterfaceStatus\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x17\n" +
	"\aarea_id\x18\x02 \x01(\tR\x06areaId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12%\n" +
	"\x0eneighbor_count\x18\x05 \x01(\rR\rneighborCount\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\rR\x04cost\"[\n" +
	"\tFRRStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\"Y\n" +
	"\x13StreamEventsRequest\x12!\n" +
	"\fowner_filter\x18\x01 \x01(\tR\vownerFilter\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"\x8f\x02\n" +
	"\n" +
	"RouteEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.novaroute.v1.EventTypeR\x04type\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.novaroute.v1.RouteEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*U\n" +
	"\bPeerType\x12\x19\n" +
	"\x15PEER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PEER_TYPE_EXTERNAL\x10\x01\x12\x16\n" +
	"\x12PEER_TYPE_INTERNAL\x10\x02*q\n" +
	"\rAddressFamily\x12\x1e\n" +
	"\x1aADDRESS_FAMILY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bADDRESS_FAMILY_IPV4_UNICAST\x10\x01\x12\x1f\n" +
	"\x1bADDRESS_FAMILY_IPV6_UNICAST\x10\x02*I\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_BGP\x10\x01\x12\x11\n" +
	"\rPROTOCOL_OSPF\x10\x02*\xb4\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_PEER_UP\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_PEER_DOWN\x10\x02\x12 \n" +
	"\x1cEVENT_TYPE_PREFIX_ADVERTISED\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_PREFIX_WITHDRAWN\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_BFD_UP\x10\x05\x12\x17\n" +
	"\x13EVENT_TYPE_BFD_DOWN\x10\x06\x12\x1f\n" +
	"\x1bEVENT_TYPE_OSPF_NEIGHBOR_UP\x10\a\x12!\n" +
	"\x1dEVENT_TYPE_OSPF_NEIGHBOR_DOWN\x10\b\x12\x1c\n" +
	"\x18EVENT_TYPE_FRR_CONNECTED\x10\t\x12\x1f\n" +
	"\x1bEVENT_TYPE_FRR_DISCONNECTED\x10\n" +
	"\x12\x1f\n" +
	"\x1bEVENT_TYPE_OWNER_REGISTERED\x10\v\x12!\n" +
	"\x1dEVENT_TYPE_OWNER_DEREGISTERED\x10\f\x12\x1f\n" +
	"\x1bEVENT_TYPE_POLICY_VIOLATION\x10\r2\xbe\b\n" +
	"\fRouteControl\x12I\n" +
	"\bRegister\x12\x1d.novaroute.v1.RegisterRequest\x1a\x1e.novaroute.v1.RegisterResponse\x12O\n" +
	"\n" +
	"Deregister\x12\x1f.novaroute.v1.DeregisterRequest\x1a .novaroute.v1.DeregisterResponse\x12U\n" +
	"\fConfigureBGP\x12!.novaroute.v1.ConfigureBGPRequest\x1a\".novaroute.v1.ConfigureBGPResponse\x12L\n" +
	"\tApplyPeer\x12\x1e.novaroute.v1.ApplyPeerRequest\x1a\x1f.novaroute.v1.ApplyPeerResponse\x12O\n" +
	"\n" +
	"RemovePeer\x12\x1f.novaroute.v1.RemovePeerRequest\x1a .novaroute.v1.RemovePeerResponse\x12^\n" +
	"\x0fAdvertisePrefix\x12$.novaroute.v1.AdvertisePrefixRequest\x1a%.novaroute.v1.AdvertisePrefixResponse\x12[\n" +
	"\x0eWithdrawPrefix\x12#.novaroute.v1.WithdrawPrefixRequest\x1a$.novaroute.v1.WithdrawPrefixResponse\x12L\n" +
	"\tEnableBFD\x12\x1e.novaroute.v1.EnableBFDRequest\x1a\x1f.novaroute.v1.EnableBFDResponse\x12O\n" +
	"\n" +
	"DisableBFD\x12\x1f.novaroute.v1.DisableBFDRequest\x1a .novaroute.v1.DisableBFDResponse\x12O\n" +
	"\n" +
	"EnableOSPF\x12\x1f.novaroute.v1.EnableOSPFRequest\x1a .novaroute.v1.EnableOSPFResponse\x12R\n" +
	"\vDisableOSPF\x12 .novaroute.v1.DisableOSPFRequest\x1a!.novaroute.v1.DisableOSPFResponse\x12L\n" +
	"\tGetStatus\x12\x1e.novaroute.v1.GetStatusRequest\x1a\x1f.novaroute.v1.GetStatusResponse\x12M\n" +
	"\fStreamEvents\x12!.novaroute.v1.StreamEventsRequest\x1a\x18.novaroute.v1.RouteEvent0\x01B&Z$github.com/piwi3910/NovaRoute/api/v1b\x06proto3"

var (
	file_api_v1_novaroute_proto_rawDescOnce sync.Once
	file_api_v1_novaroute_proto_rawDescData []byte
)

func file_api_v1_novaroute_proto_rawDescGZIP() []byte {
	file_api_v1_novaroute_proto_rawDescOnce.Do(func() {
		file_api_v1_novaroute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_novaroute_proto_rawDesc), len(file_api_v1_novaroute_proto_rawDesc)))
	})
	return file_api_v1_novaroute_proto_rawDescData
}

var file_api_v1_novaroute_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_v1_novaroute_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_v1_novaroute_proto_goTypes = []any{
	(PeerType)(0),                   // 0: novaroute.v1.PeerType
	(AddressFamily)(0),              // 1: novaroute.v1.AddressFamily
	(Protocol)(0),                   // 2: novaroute.v1.Protocol
	(EventType)(0),                  // 3: novaroute.v1.EventType
	(*RegisterRequest)(nil),         // 4: novaroute.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 5: novaroute.v1.RegisterResponse
	(*DeregisterRequest)(nil),       // 6: novaroute.v1.DeregisterRequest
	(*DeregisterResponse)(nil),      // 7: novaroute.v1.DeregisterResponse
	(*ConfigureBGPRequest)(nil),     // 8: novaroute.v1.ConfigureBGPRequest
	(*ConfigureBGPResponse)(nil),    // 9: novaroute.v1.ConfigureBGPResponse
	(*ApplyPeerRequest)(nil),        // 10: novaroute.v1.ApplyPeerRequest
	(*BGPPeer)(nil),                 // 11: novaroute.v1.BGPPeer
	(*ApplyPeerResponse)(nil),       // 12: novaroute.v1.ApplyPeerResponse
	(*RemovePeerRequest)(nil),       // 13: novaroute.v1.RemovePeerRequest
	(*RemovePeerResponse)(nil),      // 14: novaroute.v1.RemovePeerResponse
	(*AdvertisePrefixRequest)(nil),  // 15: novaroute.v1.AdvertisePrefixRequest
	(*PrefixAttributes)(nil),        // 16: novaroute.v1.PrefixAttributes
	(*AdvertisePrefixResponse)(nil), // 17: novaroute.v1.AdvertisePrefixResponse
	(*WithdrawPrefixRequest)(nil),   // 18: novaroute.v1.WithdrawPrefixRequest
	(*WithdrawPrefixResponse)(nil),  // 19: novaroute.v1.WithdrawPrefixResponse
	(*EnableBFDRequest)(nil),        // 20: novaroute.v1.EnableBFDRequest
	(*EnableBFDResponse)(nil),       // 21: novaroute.v1.EnableBFDResponse
	(*DisableBFDRequest)(nil),       // 22: novaroute.v1.DisableBFDRequest
	(*DisableBFDResponse)(nil),      // 23: novaroute.v1.DisableBFDResponse
	(*EnableOSPFRequest)(nil),       // 24: novaroute.v1.EnableOSPFRequest
	(*EnableOSPFResponse)(nil),      // 25: novaroute.v1.EnableOSPFResponse
	(*DisableOSPFRequest)(nil),      // 26: novaroute.v1.DisableOSPFRequest
	(*DisableOSPFResponse)(nil),     // 27: novaroute.v1.DisableOSPFResponse
	(*GetStatusRequest)(nil),        // 28: novaroute.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 29: novaroute.v1.GetStatusResponse
	(*PeerStatus)(nil),              // 30: novaroute.v1.PeerStatus
	(*PrefixStatus)(nil),            // 31: novaroute.v1.PrefixStatus
	(*BFDSessionStatus)(nil),        // 32: novaroute.v1.BFDSessionStatus
	(*OSPFInterfaceStatus)(nil),     // 33: novaroute.v1.OSPFInterfaceStatus
	(*FRRStatus)(nil),               // 34: novaroute.v1.FRRStatus
	(*StreamEventsRequest)(nil),     // 35: novaroute.v1.StreamEventsRequest
	(*RouteEvent)(nil),              // 36: novaroute.v1.RouteEvent
	nil,                             // 37: novaroute.v1.RouteEvent.MetadataEntry
}
var file_api_v1_novaroute_proto_depIdxs = []int32{
	11, // 0: novaroute.v1.ApplyPeerRequest.peer:type_name -> novaroute.v1.BGPPeer
	0,  // 1: novaroute.v1.BGPPeer.peer_type:type_name -> novaroute.v1.PeerType
	1,  // 2: novaroute.v1.BGPPeer.address_families:type_name -> novaroute.v1.AddressFamily
	2,  // 3: novaroute.v1.AdvertisePrefixRequest.protocol:type_name -> novaroute.v1.Protocol
	16, // 4: novaroute.v1.AdvertisePrefixRequest.attributes:type_name -> novaroute.v1.PrefixAttributes
	2,  // 5: novaroute.v1.WithdrawPrefixRequest.protocol:type_name -> novaroute.v1.Protocol
	30, // 6: novaroute.v1.GetStatusResponse.peers:type_name -> novaroute.v1.PeerStatus
	31, // 7: novaroute.v1.GetStatusResponse.prefixes:type_name -> novaroute.v1.PrefixStatus
	32, // 8: novaroute.v1.GetStatusResponse.bfd_sessions:type_name -> novaroute.v1.BFDSessionStatus
	33, // 9: novaroute.v1.GetStatusResponse.ospf_interfaces:type_name -> novaroute.v1.OSPFInterfaceStatus
	34, // 10: novaroute.v1.GetStatusResponse.frr_status:type_name -> novaroute.v1.FRRStatus
	2,  // 11: novaroute.v1.PrefixStatus.protocol:type_name -> novaroute.v1.Protocol
	3,  // 12: novaroute.v1.RouteEvent.type:type_name -> novaroute.v1.EventType
	37, // 13: novaroute.v1.RouteEvent.metadata:type_name -> novaroute.v1.RouteEvent.MetadataEntry
	4,  // 14: novaroute.v1.RouteControl.Register:input_type -> novaroute.v1.RegisterRequest
	6,  // 15: novaroute.v1.RouteControl.Deregister:input_type -> novaroute.v1.DeregisterRequest
	8,  // 16: novaroute.v1.RouteControl.ConfigureBGP:input_type -> novaroute.v1.ConfigureBGPRequest
	10, // 17: novaroute.v1.RouteControl.ApplyPeer:input_type -> novaroute.v1.ApplyPeerRequest
	13, // 18: novaroute.v1.RouteControl.RemovePeer:input_type -> novaroute.v1.RemovePeerRequest
	15, // 19: novaroute.v1.RouteControl.AdvertisePrefix:input_type -> novaroute.v1.AdvertisePrefixRequest
	18, // 20: novaroute.v1.RouteControl.WithdrawPrefix:input_type -> novaroute.v1.WithdrawPrefixRequest
	20, // 21: novaroute.v1.RouteControl.EnableBFD:input_type -> novaroute.v1.EnableBFDRequest
	22, // 22: novaroute.v1.RouteControl.DisableBFD:input_type -> novaroute.v1.DisableBFDRequest
	24, // 23: novaroute.v1.RouteControl.EnableOSPF:input_type -> novaroute.v1.EnableOSPFRequest
	26, // 24: novaroute.v1.RouteControl.DisableOSPF:input_type -> novaroute.v1.DisableOSPFRequest
	28, // 25: novaroute.v1.RouteControl.GetStatus:input_type -> novaroute.v1.GetStatusRequest
	35, // 26: novaroute.v1.RouteControl.StreamEvents:input_type -> novaroute.v1.StreamEventsRequest
	5,  // 27: novaroute.v1.RouteControl.Register:output_type -> novaroute.v1.RegisterResponse
	7,  // 28: novaroute.v1.RouteControl.Deregister:output_type -> novaroute.v1.DeregisterResponse
	9,  // 29: novaroute.v1.RouteControl.ConfigureBGP:output_type -> novaroute.v1.ConfigureBGPResponse
	12, // 30: novaroute.v1.RouteControl.ApplyPeer:output_type -> novaroute.v1.ApplyPeerResponse
	14, // 31: novaroute.v1.RouteControl.RemovePeer:output_type -> novaroute.v1.RemovePeerResponse
	17, // 32: novaroute.v1.RouteControl.AdvertisePrefix:output_type -> novaroute.v1.AdvertisePrefixResponse
	19, // 33: novaroute.v1.RouteControl.WithdrawPrefix:output_type -> novaroute.v1.WithdrawPrefixResponse
	21, // 34: novaroute.v1.RouteControl.EnableBFD:output_type -> novaroute.v1.EnableBFDResponse
	23, // 35: novaroute.v1.RouteControl.DisableBFD:output_type -> novaroute.v1.DisableBFDResponse
	25, // 36: novaroute.v1.RouteControl.EnableOSPF:output_type -> novaroute.v1.EnableOSPFResponse
	27, // 37: novaroute.v1.RouteControl.DisableOSPF:output_type -> novaroute.v1.DisableOSPFResponse
	29, // 38: novaroute.v1.RouteControl.GetStatus:output_type -> novaroute.v1.GetStatusResponse
	36, // 39: novaroute.v1.RouteControl.StreamEvents:output_type -> novaroute.v1.RouteEvent
	27, // [27:40] is the sub-list for method output_type
	14, // [14:27] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_v1_novaroute_proto_init() }
func file_api_v1_novaroute_proto_init() {
	if File_api_v1_novaroute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_novaroute_proto_rawDesc), len(file_api_v1_novaroute_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_novaroute_proto_goTypes,
		DependencyIndexes: file_api_v1_novaroute_proto_depIdxs,
		EnumInfos:         file_api_v1_novaroute_proto_enumTypes,
		MessageInfos:      file_api_v1_novaroute_proto_msgTypes,
	}.Build()
	File_api_v1_novaroute_proto = out.File
	file_api_v1_novaroute_proto_goTypes = nil
	file_api_v1_novaroute_proto_depIdxs = nil
}
