// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/novaroute.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteControl_Register_FullMethodName        = "/novaroute.v1.RouteControl/Register"
	RouteControl_Deregister_FullMethodName      = "/novaroute.v1.RouteControl/Deregister"
	RouteControl_ConfigureBGP_FullMethodName    = "/novaroute.v1.RouteControl/ConfigureBGP"
	RouteControl_ApplyPeer_FullMethodName       = "/novaroute.v1.RouteControl/ApplyPeer"
	RouteControl_RemovePeer_FullMethodName      = "/novaroute.v1.RouteControl/RemovePeer"
	RouteControl_AdvertisePrefix_FullMethodName = "/novaroute.v1.RouteControl/AdvertisePrefix"
	RouteControl_WithdrawPrefix_FullMethodName  = "/novaroute.v1.RouteControl/WithdrawPrefix"
	RouteControl_EnableBFD_FullMethodName       = "/novaroute.v1.RouteControl/EnableBFD"
	RouteControl_DisableBFD_FullMethodName      = "/novaroute.v1.RouteControl/DisableBFD"
	RouteControl_EnableOSPF_FullMethodName      = "/novaroute.v1.RouteControl/EnableOSPF"
	RouteControl_DisableOSPF_FullMethodName     = "/novaroute.v1.RouteControl/DisableOSPF"
	RouteControl_GetStatus_FullMethodName       = "/novaroute.v1.RouteControl/GetStatus"
	RouteControl_StreamEvents_FullMethodName    = "/novaroute.v1.RouteControl/StreamEvents"
)

// RouteControlClient is the client API for RouteControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouteControl is the main NovaRoute API service.
// Clients (NovaEdge, NovaNet, Admin) connect via Unix domain socket
// at /run/novaroute/novaroute.sock to manage routing intents.
type RouteControlClient interface {
	// Session management
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// BGP global configuration
	ConfigureBGP(ctx context.Context, in *ConfigureBGPRequest, opts ...grpc.CallOption) (*ConfigureBGPResponse, error)
	// Peer management
	ApplyPeer(ctx context.Context, in *ApplyPeerRequest, opts ...grpc.CallOption) (*ApplyPeerResponse, error)
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	// Prefix advertisement
	AdvertisePrefix(ctx context.Context, in *AdvertisePrefixRequest, opts ...grpc.CallOption) (*AdvertisePrefixResponse, error)
	WithdrawPrefix(ctx context.Context, in *WithdrawPrefixRequest, opts ...grpc.CallOption) (*WithdrawPrefixResponse, error)
	// BFD
	EnableBFD(ctx context.Context, in *EnableBFDRequest, opts ...grpc.CallOption) (*EnableBFDResponse, error)
	DisableBFD(ctx context.Context, in *DisableBFDRequest, opts ...grpc.CallOption) (*DisableBFDResponse, error)
	// OSPF
	EnableOSPF(ctx context.Context, in *EnableOSPFRequest, opts ...grpc.CallOption) (*EnableOSPFResponse, error)
	DisableOSPF(ctx context.Context, in *DisableOSPFRequest, opts ...grpc.CallOption) (*DisableOSPFResponse, error)
	// Observability
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteEvent], error)
}

type routeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteControlClient(cc grpc.ClientConnInterface) RouteControlClient {
	return &routeControlClient{cc}
}

func (c *routeControlClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RouteControl_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, RouteControl_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) ConfigureBGP(ctx context.Context, in *ConfigureBGPRequest, opts ...grpc.CallOption) (*ConfigureBGPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureBGPResponse)
	err := c.cc.Invoke(ctx, RouteControl_ConfigureBGP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) ApplyPeer(ctx context.Context, in *ApplyPeerRequest, opts ...grpc.CallOption) (*ApplyPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPeerResponse)
	err := c.cc.Invoke(ctx, RouteControl_ApplyPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, RouteControl_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) AdvertisePrefix(ctx context.Context, in *AdvertisePrefixRequest, opts ...grpc.CallOption) (*AdvertisePrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvertisePrefixResponse)
	err := c.cc.Invoke(ctx, RouteControl_AdvertisePrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) WithdrawPrefix(ctx context.Context, in *WithdrawPrefixRequest, opts ...grpc.CallOption) (*WithdrawPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawPrefixResponse)
	err := c.cc.Invoke(ctx, RouteControl_WithdrawPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) EnableBFD(ctx context.Context, in *EnableBFDRequest, opts ...grpc.CallOption) (*EnableBFDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableBFDResponse)
	err := c.cc.Invoke(ctx, RouteControl_EnableBFD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) DisableBFD(ctx context.Context, in *DisableBFDRequest, opts ...grpc.CallOption) (*DisableBFDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableBFDResponse)
	err := c.cc.Invoke(ctx, RouteControl_DisableBFD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) EnableOSPF(ctx context.Context, in *EnableOSPFRequest, opts ...grpc.CallOption) (*EnableOSPFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableOSPFResponse)
	err := c.cc.Invoke(ctx, RouteControl_EnableOSPF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) DisableOSPF(ctx context.Context, in *DisableOSPFRequest, opts ...grpc.CallOption) (*DisableOSPFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableOSPFResponse)
	err := c.cc.Invoke(ctx, RouteControl_DisableOSPF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RouteControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeControlClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouteControl_ServiceDesc.Streams[0], RouteControl_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, RouteEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteControl_StreamEventsClient = grpc.ServerStreamingClient[RouteEvent]

// RouteControlServer is the server API for RouteControl service.
// All implementations must embed UnimplementedRouteControlServer
// for forward compatibility.
//
// RouteControl is the main NovaRoute API service.
// Clients (NovaEdge, NovaNet, Admin) connect via Unix domain socket
// at /run/novaroute/novaroute.sock to manage routing intents.
type RouteControlServer interface {
	// Session management
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// BGP global configuration
	ConfigureBGP(context.Context, *ConfigureBGPRequest) (*ConfigureBGPResponse, error)
	// Peer management
	ApplyPeer(context.Context, *ApplyPeerRequest) (*ApplyPeerResponse, error)
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	// Prefix advertisement
	AdvertisePrefix(context.Context, *AdvertisePrefixRequest) (*AdvertisePrefixResponse, error)
	WithdrawPrefix(context.Context, *WithdrawPrefixRequest) (*WithdrawPrefixResponse, error)
	// BFD
	EnableBFD(context.Context, *EnableBFDRequest) (*EnableBFDResponse, error)
	DisableBFD(context.Context, *DisableBFDRequest) (*DisableBFDResponse, error)
	// OSPF
	EnableOSPF(context.Context, *EnableOSPFRequest) (*EnableOSPFResponse, error)
	DisableOSPF(context.Context, *DisableOSPFRequest) (*DisableOSPFResponse, error)
	// Observability
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[RouteEvent]) error
	mustEmbedUnimplementedRouteControlServer()
}

// UnimplementedRouteControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteControlServer struct{}

func (UnimplementedRouteControlServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRouteControlServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedRouteControlServer) ConfigureBGP(context.Context, *ConfigureBGPRequest) (*ConfigureBGPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureBGP not implemented")
}
func (UnimplementedRouteControlServer) ApplyPeer(context.Context, *ApplyPeerRequest) (*ApplyPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPeer not implemented")
}
func (UnimplementedRouteControlServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedRouteControlServer) AdvertisePrefix(context.Context, *AdvertisePrefixRequest) (*AdvertisePrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertisePrefix not implemented")
}
func (UnimplementedRouteControlServer) WithdrawPrefix(context.Context, *WithdrawPrefixRequest) (*WithdrawPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawPrefix not implemented")
}
func (UnimplementedRouteControlServer) EnableBFD(context.Context, *EnableBFDRequest) (*EnableBFDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableBFD not implemented")
}
func (UnimplementedRouteControlServer) DisableBFD(context.Context, *DisableBFDRequest) (*DisableBFDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableBFD not implemented")
}
func (UnimplementedRouteControlServer) EnableOSPF(context.Context, *EnableOSPFRequest) (*EnableOSPFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableOSPF not implemented")
}
func (UnimplementedRouteControlServer) DisableOSPF(context.Context, *DisableOSPFRequest) (*DisableOSPFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableOSPF not implemented")
}
func (UnimplementedRouteControlServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRouteControlServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[RouteEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRouteControlServer) mustEmbedUnimplementedRouteControlServer() {}
func (UnimplementedRouteControlServer) testEmbeddedByValue()                      {}

// UnsafeRouteControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteControlServer will
// result in compilation errors.
type UnsafeRouteControlServer interface {
	mustEmbedUnimplementedRouteControlServer()
}

func RegisterRouteControlServer(s grpc.ServiceRegistrar, srv RouteControlServer) {
	// If the following call panics, it indicates UnimplementedRouteControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteControl_ServiceDesc, srv)
}

func _RouteControl_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_ConfigureBGP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureBGPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).ConfigureBGP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_ConfigureBGP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).ConfigureBGP(ctx, req.(*ConfigureBGPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_ApplyPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).ApplyPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_ApplyPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).ApplyPeer(ctx, req.(*ApplyPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_AdvertisePrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertisePrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).AdvertisePrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_AdvertisePrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).AdvertisePrefix(ctx, req.(*AdvertisePrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_WithdrawPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).WithdrawPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_WithdrawPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).WithdrawPrefix(ctx, req.(*WithdrawPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_EnableBFD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableBFDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).EnableBFD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_EnableBFD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).EnableBFD(ctx, req.(*EnableBFDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_DisableBFD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableBFDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).DisableBFD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_DisableBFD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).DisableBFD(ctx, req.(*DisableBFDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_EnableOSPF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableOSPFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).EnableOSPF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_EnableOSPF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).EnableOSPF(ctx, req.(*EnableOSPFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_DisableOSPF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableOSPFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).DisableOSPF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_DisableOSPF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).DisableOSPF(ctx, req.(*DisableOSPFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteControlServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteControl_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteControlServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, RouteEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteControl_StreamEventsServer = grpc.ServerStreamingServer[RouteEvent]

// RouteControl_ServiceDesc is the grpc.ServiceDesc for RouteControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novaroute.v1.RouteControl",
	HandlerType: (*RouteControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RouteControl_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _RouteControl_Deregister_Handler,
		},
		{
			MethodName: "ConfigureBGP",
			Handler:    _RouteControl_ConfigureBGP_Handler,
		},
		{
			MethodName: "ApplyPeer",
			Handler:    _RouteControl_ApplyPeer_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _RouteControl_RemovePeer_Handler,
		},
		{
			MethodName: "AdvertisePrefix",
			Handler:    _RouteControl_AdvertisePrefix_Handler,
		},
		{
			MethodName: "WithdrawPrefix",
			Handler:    _RouteControl_WithdrawPrefix_Handler,
		},
		{
			MethodName: "EnableBFD",
			Handler:    _RouteControl_EnableBFD_Handler,
		},
		{
			MethodName: "DisableBFD",
			Handler:    _RouteControl_DisableBFD_Handler,
		},
		{
			MethodName: "EnableOSPF",
			Handler:    _RouteControl_EnableOSPF_Handler,
		},
		{
			MethodName: "DisableOSPF",
			Handler:    _RouteControl_DisableOSPF_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RouteControl_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _RouteControl_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/novaroute.proto",
}
