{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "novaroute.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novaroute.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "novaroute.fullname" . }}-agent
  labels:
    {{- include "novaroute.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "novaroute.fullname" . }}-agent
  labels:
    {{- include "novaroute.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "novaroute.fullname" . }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "novaroute.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
