apiVersion: v1
kind: Service
metadata:
  name: {{ include "novaroute.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novaroute.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "novaroute.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  ports:
    - name: metrics
      port: {{ .Values.agent.metricsPort }}
      targetPort: {{ .Values.agent.metricsPort }}
      protocol: TCP
